language: node_js
node_js:
  - '10'
install: 
  - npm install --prefix plugins/tritonse-source-firestore
  - npm install 
  - npm run-script build
  - true
deploy:
  local-dir: public
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  on:
    branch: master
