language: node_js
node_js:
  - '10'
install: 
  - npm install --prefix plugins/tritonse-source-firestore
  - npm install 
  - npm run-script build
deploy:
  local-dir: public
  provider: pages
  skip-cleanup: true
  keep-history: false
  github-token: $GITHUB_TOKEN  
  target-branch: master
  on:
    branch: source 
