version: 2 
jobs: 
  build:
    working_directory: ~/website
    docker: 
      - image: circleci/node:12
    steps: 
      - checkout
      - run:
          name: Installing deployment dependencies
          command: sudo apt-get install sshpass
      - run:
          name: Installing latest version of NPM
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Installing website dependencies
          command: npm install
      - run: 
          name: Building website
          command: npm run-script build 
          environment:
            NODE_TLS_REJECT_UNAUTHORIZED: 0
  deploy: 
    working_directory: ~/website
    docker: 
      - image: circleci/node:12
    steps: 
      - add_ssh_keys:
          fingerprints:
            - "f3:c6:13:c0:cd:b7:4f:4f:e4:b2:e5:8c:48:74:3a:9a"
      - run: 
          name: Deploying to GitHub Pages
          command: 'sh .circleci/github_pages.sh'
      - run:
          name: Cleaning up stale remote server
          command: sshpass -e ssh -o StrictHostKeyChecking=no tse@acsweb.ucsd.edu 'sh clean.sh'
      - run:
          name: Deploying to remote server
          command: sshpass -e scp -o StrictHostKeyChecking=no -r . tse@acsweb.ucsd.edu:public_html
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
