version: 2.1 
general:
  branches:
    only:
      - source 
jobs: 
  build: 
    working_directory: ~/website
    docker: 
      - image: circleci/node:10.16.3 
    steps: 
      - checkout
      - run:
          name: Update NPM 
          command: 'sudo npm install -g npm@latest'
      - run:
          name: Install Firebase plugin dependencies
          command: npm install --prefix plugins/tritonse-source-firestore
      - run:
          name: Install website dependencies 
          command: npm install
      - run: 
          name: Build website 
          command: npm run-script build 
      - add_ssh_keys:
          fingerprints:
            - "f3:c6:13:c0:cd:b7:4f:4f:e4:b2:e5:8c:48:74:3a:9a"
      - run: 
          name: Deploy to master branch 
          command: sh scripts/circleci-deploy.sh
